server:
  port: 8080
  shutdown: GRACEFUL

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - beans
          - caches
          - configprops
          - env
          - health
          - info
          - loggers
          - mappings
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
    loggers:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    git:
      mode: SIMPLE

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database: h2

  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

